### ISSUE TITLE
Can't install versions >= 0.13.x

### ISSUE THREAD

**Issue by canha** [looztra/asdf-k9s#11]
Seems like there is a 'v' in the path now, even though the version tar doesn't have that 'v'.

Plugin tries to download:
`https://github.com/derailed/k9s/releases/download/0.13.6/k9s_0.13.6_Linux_x86_64.tar.gz`

Release is:
`https://github.com/derailed/k9s/releases/download/v0.13.6/k9s_0.13.6_Linux_x86_64.tar.gz`

**Comment by looztra** [comment]
fixed by #14
