### ISSUE TITLE
please add platform support for arm and arm64

### ISSUE THREAD

**Issue by sedlund** [looztra/asdf-k9s#21]
Thanks!

**Comment by nklmilojevic** [comment]
I added it here, should work:

https://github.com/looztra/asdf-k9s/pull/22

Tested on M1 mac.

**Comment by sedlund** [comment]
Cool!   while your there can you add:

k9s_Linux_arm.tar.gz
k9s_Linux_arm64.tar.gz

**Comment by nklmilojevic** [comment]
Rewrote the logic - should work for all cases now (including rPi).

**Comment by sedlund** [comment]
tested works fine on 32bit pi.

Thanks!

**Comment by looztra** [comment]
#22 merged, closing
